Resolves switched out of realtime warning
personalrobotics/libbarrett pull request #10
Opened 2019-12-07 01:36 UTC by madan96

The controller_manager got stuck when loading rewd_controllers and system throws the warning
'Switched out of RealTime'. Looking at `var/log/syslog`, it appears to switch out when calling the logger.log() method. Commenting out the `logger.log()` calls seems to fix the issue. But it still remains a mystery as to why this is happening.

A possible issue could be updates in system-level libraries. 
@egordon : The only thing the logger does is push to an `std::queue`, so it is possible that `std::queue` is no longer real-time safe. A possible solution could be to use `boost::lockfree::queue`

2019-12-08 03:49 UTC, brianhou commented
Thanks for finding this! I think we should just strip out the logger entirely: it's something that we added while attempting to debug the WAMs, and it looks like we weren't especially careful. (We only kept it because it didn't seem to cause problems.)

If we decide to implement it again, we should probably just figure out how to use `barrett::log::RealTimeWriter`.

2019-12-08 03:50 UTC, brianhou requested changes
I think we should strip out the logger entirely.

2019-12-12 03:18 UTC, madan96 commented
Oops! Seems like @aditya-vk configured the user details on `herb0`. Anyway, I have removed the logger and tested the f/t controller after rebuilding `libbarrett`. Works fine!

2019-12-12 19:43 UTC, brianhou commented on src/bus/can_socket-rtcan.cpp
>  std::string filename = "/home/robot/log_" + boost::lexical_cast<std::string>(startTime);;
I don't think we need these variables here (we can delete the logging and stack trace stuff from the constructor too).

2019-12-13 21:53 UTC, brianhou approved these changes

2019-12-13 21:53 UTC, brianhou commented
Thanks! Merge whenever you're satisfied.

2019-12-19 02:41 UTC, merged